[build]
  base = "."
  command = "chmod +x ./scripts/prepare-ul-network.sh && npm install && npm --prefix client install && ./scripts/prepare-ul-network.sh && npm run build"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "18"
